name: Deploy to Vercel

on:
  push:
    branches:
      - main # or your main branch
    paths:
      - 'pages/**' # Trigger only when changes are made in the pages directory
      - 'components/**' # Trigger only when changes are made in the components directory
      - 'public/**' # Trigger only when changes are made in the public directory
      - 'styles/**' # Trigger only when changes are made in the styles directory
      - 'package.json'
      - 'package-lock.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}